version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile  
    ports:
      - "8001:8001"  
    volumes:
      - ./Backend:/app 
    working_dir: /app 
    command: python manage.py runserver 0.0.0.0:8001  
    environment:
      - PYTHONUNBUFFERED=1  

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile  
    ports:
      - "8003:8003"  
    volumes:
      - ./Frontend:/app 
    working_dir: /app 
    command: streamlit run app.py --server.port=8003 --server.address=0.0.0.0  
    environment:
      - BACKEND_URL=http://backend:8001  
