# Generated by Django 5.1.2 on 2025-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='token_valid',
            field=models.BooleanField(default=True),
        ),
    ]
